name: Manually Trigger AWS CodePipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  start-codepipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::427212782605:policy/dev-pipeline
          aws-region: ap-south-1

      - name: Start AWS CodePipeline Execution
        run: |
          aws codepipeline start-pipeline-execution --name my-web-app-pipeline
